name: Release Docker Images
on:
  push:
    branches:
      - main
    paths:
      - "python/sglang/version.py"
  workflow_dispatch:

jobs:
  publish:
    if: github.repository == 'AlexDeng-AI/sglang'
    runs-on: self-hosted
    environment: 'prod'
    strategy:
      matrix:
        cuda_version: ['12.1.1']
        build_type: ['all']
    steps:
      - name: Print current user
        run: whoami

      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        run: |
          version=$(cat python/sglang/version.py | cut -d'"' -f2)

          if [ "${{ matrix.cuda_version }}" = "11.8.0" ]; then
            cuda_tag="cu118"
          elif [ "${{ matrix.cuda_version }}" = "12.1.1" ]; then
            cuda_tag="cu121"
          elif [ "${{ matrix.cuda_version }}" = "12.4.1" ]; then
            cuda_tag="cu124"
          elif [ "${{ matrix.cuda_version }}" = "12.5.1" ]; then
            cuda_tag="cu125"
          else
            echo "Unsupported CUDA version"
            exit 1
          fi

          tag=v${version}-${cuda_tag}

          if [ "${{ matrix.build_type }}" = "all" ]; then
            tag_suffix=""
          elif [ "${{ matrix.build_type }}" = "srt" ]; then
            tag_suffix="-srt"
          else
            echo "Unsupported build type"
            exit 1
          fi

          docker build --progress=plain  . -f docker/Dockerfile --build-arg HTTP_PROXY=http://192.168.1.31:7890   --build-arg HTTPS_PROXY=http://192.168.1.31:7890   --build-arg NO_PROXY=localhost,127.0.0.1 --build-arg CUDA_VERSION=${{ matrix.cuda_version }} --build-arg BUILD_TYPE=${{ matrix.build_type }} -t lmsysorg/sglang:${tag}${tag_suffix} --no-cache

          if [ "${{ matrix.cuda_version }}" = "12.5.1" ]; then
            docker tag lmsysorg/sglang:${tag}${tag_suffix} lmsysorg/sglang:latest${tag_suffix}
          fi
